apiVersion: v1
kind: ServiceAccount
metadata:
  name: gatekeeper-policy-manager
  namespace: gatekeeper-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatekeeper-policy-manager-crd-view
rules:
- apiGroups:
  - constraints.gatekeeper.sh
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - templates.gatekeeper.sh
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.gatekeeper.sh
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gatekeeper-policy-manager-crd-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gatekeeper-policy-manager-crd-view
subjects:
- kind: ServiceAccount
  name: gatekeeper-policy-manager
  namespace: gatekeeper-system
---
apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-policy-manager
  namespace: gatekeeper-system
spec:
  ports:
  - port: 80
    targetPort: http
  selector:
    app: gatekeeper-policy-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper-policy-manager
  namespace: gatekeeper-system
spec:
  selector:
    matchLabels:
      app: gatekeeper-policy-manager
  template:
    metadata:
      labels:
        app: gatekeeper-policy-manager
    spec:
      containers:
      - image: quay.io/sighup/gatekeeper-policy-manager:v0.5.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: http
        name: gatekeeper-policy-manager
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
      serviceAccountName: gatekeeper-policy-manager
