apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NamespaceRequireLabels
metadata:
  name: ns-must-have-kcd-italy-label
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    labels: ["kcd-italy"]
