apiVersion: constraints.gatekeeper.sh/v1beta1
kind: TrustedImageRegistry
metadata:
  name: all-pods-from-sighup-registry
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    # namespaces:
    #   - "default"
  parameters:
    registry: "registry.sighup.io"
    
